/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.25
 * Generated at: 2026-09-11 19:46:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("    <!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>EcoAgro - Tu Mercado del Campo</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<!-- Navbar -->\r\n");
      out.write("<body>\r\n");
      out.write("    <nav class=\"navbar_main navbar navbar-expand-md bg-body-tertiary\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <!-- Logo de la empresa -->\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"index.jsp \"><img src=\"imagenes/logo Ecoagro.jpg\" alt=\"logo ecoagro\" width=\"50\" height=\"50\" class=\"rounded-2\"></a>\r\n");
      out.write("            <!-- Barra de bÃºsqueda -->\r\n");
      out.write("            <nav class=\"navbar bg-body-tertiary rounded-2 order-3 order-sm-0\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <form class=\"d-flex\" role=\"search\">\r\n");
      out.write("                        <input class=\"form-control me-2 rounded-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\"/>\r\n");
      out.write("                        <button class=\"btn btn-outline-success\" type=\"submit\"><img class=\"my-auto\" src=\"imagenes/lupa.png\" alt=\"Buscar\" width=\"20\" height=\"20\"></button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!-- BotÃ³n para colapsar el menÃº en pantallas pequeÃ±as -->\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNavAltMarkup\" aria-controls=\"navbarNavAltMarkup\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <img src=\"imagenes/icono-collapse.png\" alt=\"menu\" width=\"50\" height=\"50\"></button>\r\n");
      out.write("        </button>\r\n");
      out.write("        <!-- Enlaces de navegacion -->\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarNavAltMarkup\">\r\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"text_nav nav-link\" href=\"products/catalogo_productos.html\">catalogo</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"text_nav nav-link\" href=\"login.jsp\">login</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"text_nav nav-link\" href=\"sign_up.jsp\">crear cuenta</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"products/shopping_cart.html\"><img src=\"imagenes/carrito-de-compras.png\" alt=\"carrito_de_compras\" width=\"20\" height=\"20\"></a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"products/configuracion.html\"><img src=\"imagenes/configuracion.png\" alt=\"configuracion\" width=\"20\" height=\"20\"></a>\r\n");
      out.write("        </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Contenido principal de la pÃ¡gina -->\r\n");
      out.write("<div id=\"carruselProductos\" class=\"carousel slide container mt-5 position-relative\" data-bs-ride=\"carousel\" style=\"max-width: 1200px;\">\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"carousel-inner px-5\"> <div class=\"carousel-item active\">\r\n");
      out.write("            <div class=\"row g-3 justify-content-center\"> <div class=\"col-md-4 d-flex justify-content-center\">\r\n");
      out.write("                    <div class=\"target_product card shadow-sm border-0 rounded-3 p-2\" style=\"width: 18rem;\">\r\n");
      out.write("                        <a href=\"products/pagina_producto.html\" class=\"text-decoration-none text-dark\">\r\n");
      out.write("                            <img src=\"imagenes/imagen_ejemplo_producto_1.jpg\" class=\"card-img-top img-fluid\" alt=\"Nutrimon\">\r\n");
      out.write("                            <div class=\"card-body text-center\">\r\n");
      out.write("                                <h5 class=\"card-title fw-bold\">Producto de Ejemplo</h5>\r\n");
      out.write("                                <h6 class=\"card-subtitle mb-2 text-muted\">Precio: $XX.XX</h6>\r\n");
      out.write("                                <p class=\"card-text text-muted small\">DescripciÃ³n del producto.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-4 d-flex justify-content-center\">\r\n");
      out.write("                    <div class=\"target_product card shadow-sm border-0 rounded-3 p-2\" style=\"width: 18rem;\">\r\n");
      out.write("                        <a href=\"products/pagina_producto.html\" class=\"text-decoration-none text-dark\">\r\n");
      out.write("                            <img src=\"imagenes/imagen_ejemplo_producto_2.jpg\" class=\"card-img-top img-fluid\" alt=\"Compost\">\r\n");
      out.write("                            <div class=\"card-body text-center\">\r\n");
      out.write("                                <h5 class=\"card-title fw-bold\">Producto de Ejemplo</h5>\r\n");
      out.write("                                <h6 class=\"card-subtitle mb-2 text-muted\">Precio: $XX.XX</h6>\r\n");
      out.write("                                <p class=\"card-text text-muted small\">DescripciÃ³n del producto.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-4 d-flex justify-content-center\">\r\n");
      out.write("                    <div class=\"target_product card shadow-sm border-0 rounded-3 p-2\" style=\"width: 18rem;\">\r\n");
      out.write("                        <a href=\"products/pagina_producto.html\" class=\"text-decoration-none text-dark\">\r\n");
      out.write("                            <img src=\"imagenes/imagen_ejemplo_producto_3.jpg\" class=\"card-img-top img-fluid\" alt=\"Avisana\">\r\n");
      out.write("                            <div class=\"card-body text-center\">\r\n");
      out.write("                                <h5 class=\"card-title fw-bold\">Producto de Ejemplo</h5>\r\n");
      out.write("                                <h6 class=\"card-subtitle mb-2 text-muted\">Precio: $XX.XX</h6>\r\n");
      out.write("                                <p class=\"card-text text-muted small\">DescripciÃ³n del producto.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div> </div> <div class=\"carousel-item\">\r\n");
      out.write("            <div class=\"row g-3 justify-content-center\">\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"col-md-4 d-flex justify-content-center\">\r\n");
      out.write("                    <div class=\"target_product card shadow-sm border-0 rounded-3 p-2\" style=\"width: 18rem;\">\r\n");
      out.write("                        <a href=\"products/pagina_producto.html\" class=\"text-decoration-none text-dark\">\r\n");
      out.write("                            <img src=\"imagenes/imagen_ejemplo_producto_4.jpg\" class=\"card-img-top img-fluid\" alt=\"Humus\">\r\n");
      out.write("                            <div class=\"card-body text-center\">\r\n");
      out.write("                                <h5 class=\"card-title fw-bold\">Producto de Ejemplo</h5>\r\n");
      out.write("                                <h6 class=\"card-subtitle mb-2 text-muted\">Precio: $XX.XX</h6>   \r\n");
      out.write("                                <p class=\"card-text text-muted small\">DescripciÃ³n del producto.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                </div> </div> </div> <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carruselProductos\" data-bs-slide=\"prev\" style=\"width: 5%;\">\r\n");
      out.write("        <span class=\"carousel-control-prev-icon bg-secondary rounded-circle shadow\" aria-hidden=\"true\"></span>\r\n");
      out.write("        <span class=\"visually-hidden\">Anterior</span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carruselProductos\" data-bs-slide=\"next\" style=\"width: 5%;\">\r\n");
      out.write("        <span class=\"carousel-control-next-icon bg-secondary rounded-circle shadow\" aria-hidden=\"true\"></span>\r\n");
      out.write("        <span class=\"visually-hidden\">Siguiente</span>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("</div> ```\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
