/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.25
 * Generated at: 2026-09-10 00:50:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <title>EcoAgro - Tu Mercado del Campo</title>\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    </head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Navbar -->\r\n");
      out.write("<nav class=\"navbar_main navbar navbar-expand-md bg-body-tertiary\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("    <!-- Logo de la empresa -->\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"index.html\"><img src=\"imagenes/logo Ecoagro.jpg\" alt=\"logo ecoagro\" width=\"50\" height=\"50\" class=\"rounded-2\"></a>\r\n");
      out.write("    <!-- Barra de bÃºsqueda -->\r\n");
      out.write("        <nav class=\"navbar bg-body-tertiary rounded-2 order-3 order-sm-0\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <form class=\"d-flex\" role=\"search\">\r\n");
      out.write("            <input class=\"form-control me-2 rounded-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\"/>\r\n");
      out.write("            <button class=\"btn btn-outline-success\" type=\"submit\"><img class=\"my-auto\" src=\"imagenes/lupa.png\" alt=\"Buscar\" width=\"20\" height=\"20\"></button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!-- BotÃ³n para colapsar el menÃº en pantallas pequeÃ±as -->\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNavAltMarkup\" aria-controls=\"navbarNavAltMarkup\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <img src=\"imagenes/icono-collapse.png\" alt=\"menu\" width=\"50\" height=\"50\"></button>\r\n");
      out.write("            </button>\r\n");
      out.write("    <!-- Enlaces de navegaciÃ³n -->\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarNavAltMarkup\">\r\n");
      out.write("        <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"text_nav nav-link\" href=\"products/catalogo_productos.html\">catalogo</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"text_nav nav-link\" href=\"register.html\">crear cuenta</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"products/shopping_cart.html\"><img src=\"imagenes/carrito-de-compras.png\" alt=\"carrito_de_compras\" width=\"20\" height=\"20\"></a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("            <a class=\"nav-link\" href=\"products/configuracion.html\"><img src=\"imagenes/configuracion.png\" alt=\"configuracion\" width=\"20\" height=\"20\"></a>\r\n");
      out.write("        </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container d-flex justify-content-center align-items-center vh-100\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("<!-- El recuadro del login -->\r\n");
      out.write("    <div class=\"card shadow p-4\" style=\"width: 100%; max-width: 400px;\">\r\n");
      out.write("        <div class=\"card-body\">\r\n");
      out.write("        <h3 class=\"text-center mb-4\">Iniciar Sesión</h3>\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("            ");
 
                String error = (String) request.getAttribute("errorAuth"); 
                if (error != null) { 
            
      out.write("\r\n");
      out.write("        <!-- Usamos las clases de Bootstrap para mostrar un cuadro de alerta rojo -->\r\n");
      out.write("            <div class=\"alert alert-danger text-center mb-3\" role=\"alert\">\r\n");
      out.write("            ");
      out.print( error );
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("        <form action=\"login\" method=\"POST\">\r\n");
      out.write("        <!-- Campo de Correo -->\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"inputCorreo\" class=\"form-label\">Correo Electronico</label>\r\n");
      out.write("                <input type=\"email\" class=\"form-control\" name= \"email\" id=\"inputCorreo\" placeholder=\"ejemplo@correo.com\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Campo de ContraseÃ±a -->\r\n");
      out.write("            <div class=\"mb-4\">\r\n");
      out.write("                <label for=\"inputPassword\" class=\"form-label\">Contraseña</label>\r\n");
      out.write("                <input type=\"password\" class=\"form-control\" name=\"password\" id=\"inputPassword\" placeholder=\"********\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- BotÃ³n de Ingresar -->\r\n");
      out.write("            <div class=\"d-grid\">\r\n");
      out.write("                <button type=\"submit\" class=\"btn_submit btn btn-primary\">Ingresar</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
